FROM public.ecr.aws/lambda/python:3.11

# Instala dependencias del sistema necesarias para WeasyPrint
RUN yum install -y \
    cairo \
    pango \
    gdk-pixbuf2 \
    libffi-devel \
    libjpeg-turbo-devel \
    libxml2 \
    libxslt \
    fontconfig \
    && yum clean all

# Copia tu código y dependencias Python
COPY . ${LAMBDA_TASK_ROOT}/

RUN pip install --target "${LAMBDA_TASK_ROOT}" weasyprint boto3

CMD ["lambda_function.lambda_handler"]
